import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="app">
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* Navigation */}
      {/* Main -> Results of the API */}
      {/* Footer */}

    </div>
  )
}
