import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="app">
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>create hulu app</h1>

      {/* Header */}
      {/* Navigation */}
      {/* Main -> Results of the API */}
      {/* Footer */}

    </div>
  )
}
